# Generated by Django 2.1.1 on 2018-10-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4_app', '0003_product_sales_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.TextField(null=True),
        ),
    ]
