# Generated by Django 2.1.1 on 2018-10-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project4_app', '0005_auto_20181010_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
